######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 5 16:22:59 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exp1.cpp
